{{- if .Values.neo4j.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "syncratic.fullname" . }}-neo4j
  labels:
    {{- include "syncratic.labels" . | nindent 4 }}
spec:
  type: {{ .Values.neo4j.service.type }}
  selector:
    {{- include "syncratic.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: neo4j
  ports:
    - name: http
      port: {{ .Values.neo4j.service.httpPort }}
      targetPort: http
    - name: bolt
      port: {{ .Values.neo4j.service.boltPort }}
      targetPort: bolt
{{- end }}
