{{- if and .Values.observability.enabled .Values.observability.grafana.persistence.enabled (not .Values.observability.grafana.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "syncratic.observabilityGrafanaPvcName" . }}
  labels:
    {{- include "syncratic.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.observability.grafana.persistence.size }}
  {{- with .Values.observability.grafana.persistence.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
{{- end }}
