{{- if .Values.observability.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "syncratic.observabilityGrafanaProvisioningConfigMapName" . }}
  labels:
    {{- include "syncratic.labels" . | nindent 4 }}
data:
  datasources.yml: |
    apiVersion: 1
    datasources:
    {{- if .Values.observability.grafana.datasources.prometheus.enabled }}
      - name: Prometheus
        uid: prometheus
        type: prometheus
        access: proxy
        url: {{ .Values.observability.grafana.datasources.prometheus.url | quote }}
        isDefault: {{ .Values.observability.grafana.datasources.prometheus.isDefault }}
        editable: true
    {{- end }}
    {{- if .Values.observability.grafana.datasources.loki.enabled }}
      - name: Loki
        uid: loki
        type: loki
        access: proxy
        url: {{ .Values.observability.grafana.datasources.loki.url | quote }}
        editable: true
    {{- end }}
  dashboards.yml: |
    apiVersion: 1
    providers:
    {{- if .Values.observability.grafana.dashboards.providerEnabled }}
      - name: Syncratic Observability
        orgId: 1
        folder: Syncratic
        type: file
        disableDeletion: false
        editable: true
        allowUiUpdates: true
        options:
          path: /var/lib/grafana/dashboards
    {{- else }}
      []
    {{- end }}
{{- end }}
