{{- if .Values.observability.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "syncratic-phase1.observabilityGrafanaName" . }}
  labels:
    {{- include "syncratic-phase1.labels" . | nindent 4 }}
spec:
  type: {{ .Values.observability.grafana.service.type }}
  selector:
    {{- include "syncratic-phase1.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: observability-grafana
  ports:
    - name: http
      port: {{ .Values.observability.grafana.service.port }}
      targetPort: http
{{- end }}
