{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "syncratic-phase1.fullname" . }}-postgres
  labels:
    {{- include "syncratic-phase1.labels" . | nindent 4 }}
spec:
  type: {{ .Values.postgres.service.type }}
  selector:
    {{- include "syncratic-phase1.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
  ports:
    - name: postgres
      port: {{ .Values.postgres.service.port }}
      targetPort: postgres
{{- end }}
