parent=keycloak.v2
import=common/keycloak

styles=css/syncratic.css
scripts=js/passwordVisibility.js

kcBodyClass=syncratic-kc-body
kcHeaderClass=syncratic-kc-header
kcHeaderWrapperClass=syncratic-kc-header-wrapper
